name: iv_project_api
description: "IV Project API"
version: 0.1.1
homepage:
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  iv_project_model:
    path: ../iv_project_model

  iv_project_api_core:
    path: ../iv_project_api_core

  path: ^1.9.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
